# -*- coding: utf-8 -*-
"""Praticando.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YHavLl9V_YvniAiUbT8CRg_Dzd-tkRPM
"""

while True:
  a = int(input("Digite um número:"))
  b = int(input("Digite outro número:"))
  print ("Você escolheu os números", a, "e", b)
  soma = a + b
  sub = a - b
  mult = a * b
  divisao = a / b


 #interface
  print ("Escolha uma opção:")
  print ("1. Soma")
  print ("2. Subtração")
  print ("3. Multiplicação")
  print ("4. Divisão")
  print ("5. Sair")
  escolha = input("Digite o número da opção desejada:")

 #opções para chamar as operações
  if escolha == "1":
    print("A soma dos valores é", soma)
  elif escolha == "2":
    print("A diferença dos valores é", sub)
  elif escolha == "3":
    print("A multiplicação dos valores é", mult)
  elif escolha == "4":
    print("A divisão dos valores é", divisao)
  elif escolha == "5":
    print ("Você escolheu encerrar o programa.")
    break
  else:
    print("Valor inválido.")